// react-ecom/src/components/Store.jsx
import React, { useEffect, useState } from 'react'
import { Col, ListGroup, ListGroupItem, Row } from 'reactstrap'
import Base from './Base'
import Product from './Product'
import { loadProducts, loadProductsByCategory } from '../services/product-service'
import { loadCategories } from '../services/category-serivce'
import { Link, useParams } from 'react-router-dom'
import InfiniteScroll from 'react-infinite-scroll-component'
import {addItemToCart as addCart} from '../services/cart-service'
import { toast } from 'react-toastify'

function Store() {


  const { categoryId } = useParams()

  const [categories, setCategories] = useState(null)
  const [productDetail, setProductDetails] = useState(null)
  const [pageNumber, setPageNumber] = useState({
    count:0
  })

  const [flag,setFlag]=useState(true)

  useEffect(() => { 
       
    if(flag){
      console.log("Initial time")
      getCategories()
      setFlag(false)
    } else{
      console.log("Not initial time")
      setProductDetails(null)
      setPageNumber({count:0})
      
    }   
    console.log(categoryId)
  }, [categoryId])


 

  useEffect(() => {
    console.log("Page number :"+pageNumber.count)
    getProducts(pageNumber.count)
  }, [pageNumber])


  const getProducts = (pageNumber) => {
    let ob = null
    if (categoryId === 'all') {
      ob = loadProducts(pageNumber)
    } else {
      ob = loadProductsByCategory(categoryId, pageNumber)
    }

    ob.then(data => {
      console.log(data);
      if (productDetail) {

        setProductDetails({
          content: [...productDetail.content, ...data.content],
          lastPage: data.lastPage,
          pageNumber: data.pageNumber,
          pageSize: data.pageSize,
          totalElements: data.totalElements,
          totalPages: data.totalPages
        })

      } else {
        setProductDetails(data)
      }

    })
      .catch(error => {
        console.log(error)
      })
  }

  const getCategories = () => {
    loadCategories()
      .then(data => {
        console.log(data);
        setCategories(data)
      })
      .catch(error => {
        console.log(error)
      })
  }

  const loadMoreComponent = () => {
    console.log("loading more")
    setPageNumber({ count:pageNumber.count+1 })

  }

  //add item to card
  const addItemToCart=(product)=>{
    console.log(product)
    addCart(product.productId,1)
    .then((data)=>{
      console.log(data)
      toast.success("Item Added to Cart")
    }).catch(error=>{
      console.log(error)
    })
    
  }

  const getInfiniteScrollWitContent = () => {
    return (<InfiniteScroll
      dataLength={productDetail.content.length}
      next={loadMoreComponent}
      hasMore={!productDetail.lastPage}
      loader={<h4>Loading...</h4>}
    >

      <Row>
        {
          (productDetail) &&
          productDetail.content.map((item, index) => (
            <Col md="6" lg="4" key={index}>

              <Product addToCart={addItemToCart} product={item} />

            </Col>
          ))
        }
      </Row>
    </InfiniteScroll>)
  }

  return (
    <Base>

      <div className="container-fluid px-5 mt-4">

        <Row className='mt-3'>


          <Col md="3">
            <h1>Categories</h1>

            <ListGroup>
              <ListGroupItem action tag={Link} to="/store/all">All</ListGroupItem>

              {
                (categories) && categories.map(cat => (
                  <ListGroupItem action tag={Link} to={'/store/' + cat.categoryId} key={cat.categoryId}>{cat.title}</ListGroupItem>
                ))
              }

            </ListGroup>

          </Col>

          <Col md="9">
            <h1>Products</h1>


            {productDetail && getInfiniteScrollWitContent()}


          </Col>

        </Row>


      </div>

    </Base>
  )
}

export default Store

// angular-ecom/src/app/components/store/store.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Routes } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { Observable } from 'rxjs';
import { CartService } from 'src/app/services/cart.service';
import { CategoryService } from 'src/app/services/category.service';
import { ProductService } from 'src/app/services/product.service';

@Component({
  selector: 'app-store',
  templateUrl: './store.component.html',
  styleUrls: ['./store.component.css']
})
export class StoreComponent implements OnInit {

  categories: any
  products: any;
  categoryId: any

  constructor(
    private category: CategoryService,
    private product: ProductService,
    private toast: ToastrService,
    private route: ActivatedRoute,
    private cartService:CartService
  ) { }

  ngOnInit(): void {
    this.route.params.subscribe((values: any) => {
      this.products=undefined
      this.pageNumber=0
      console.log(values.categoryId);
      this.categoryId = values.categoryId
      this.getProducts(values.categoryId, this.pageNumber, this.pageSize)
    })
    this.getCategories()
  }


  getCategories() {
    this.category.loadCategories().subscribe({
      next: (data) => {
        //success
        console.log(data);
        this.categories = data
      },
      error: (error) => {
        //error
        console.log(error);
        this.toast.error("Error in loading categories")
      },
      complete: () => {
      }
    })

  }



  getProducts(categoryId: any, pageNumber: any, pageSize: any) {
    let ob: any
    if (categoryId.trim() === 'all') {
      ob = this.product.loadProducts(pageSize = pageSize, pageNumber = pageNumber)
    } else {
      ob = this.product.loadProductsByCategory(categoryId, pageSize = pageSize, pageNumber = pageNumber)
    }
    ob.subscribe({
      next: (data: any) => {
        console.log(data);
        if (this.products) {
          //already data is there
          this.products.content = this.products.content.concat(data.content)
          this.products.lastPage = data.lastPage
          this.products.pageNumber = data.pageNumber
          this.products.pageSize = data.pageSize
          this.products.totalElements = data.totalElements
          this.products.totalPages = data.totalPages

        } else {
          //first time
          this.products = data
        }
        this.loading=false

      },
      error: (error: any) => {
        console.log(error);
        this.toast.error("Error in loading products")
        this.loading=false
      }
    })
  }

  pageNumber = 0
  pageSize = 30
  loading=false
  onScroll() {

    if (this.products.lastPage) {
      console.log("already at last page");
      return
    }

    this.loading=true

    setTimeout(() => {

      this.pageNumber = this.pageNumber + 1;
      console.log("page scrolled " + this.pageNumber);
      this.getProducts(this.categoryId, this.pageNumber, this.pageSize)


    }, 1000);


  }


  //add item to card

  addToCart(product:any){
    console.log(product)
    this.cartService.addItemToCart(product.productId,1).subscribe({
      next:data=>{
        console.log(data);
        this.toast.success("Item added to card")
        
      },
      error:error=>{
        console.log(error);
        this.toast.error("Error while adding to cart")
        
      }
    })
  }

}

<div class="container-fluid">
  <div class="row p-5">
    <div class="col-md-3">
      <h1>Categories</h1>

      <div class="list-group border-0 shadow-sm">
        <a
          class="list-group-item border border-bottom-1"
          routerLink="/store/all"
        >
          All
        </a>

        <a
          [routerLink]="'/store/' + c.categoryId"
          *ngFor="let c of categories"
          href=""
          class="list-group-item border border-bottom-1"
        >
          {{ c.title }}
        </a>
      </div>
    </div>

    <div class="col-md-9">
      <h1>Products</h1>

      <div
        class="row"
        *ngIf="products"
        infiniteScroll
        [infiniteScrollDistance]="2"
        [infiniteScrollThrottle]="1000"
        (scrolled)="onScroll()"
      >
        <div class="col-md-6 col-lg-4" *ngFor="let p of products.content">
          <app-product [product]="p"  (productAddedEvent)="addToCart($event)" ></app-product>
        </div>
      </div>

      <h1 class="text-center my-3" *ngIf="loading">Please products loading....</h1>

    </div>
  </div>
</div>
