// react-ecom/src/components/CustomNavbar.jsx
import React, {useState} from 'react'
import {NavLink as ReactLink, useNavigate} from 'react-router-dom'
import {
    Collapse,
    Navbar,
    NavbarToggler,
    NavbarBrand,
    Nav,
    NavItem,
    NavLink,
    UncontrolledDropdown,
    DropdownToggle,
    DropdownMenu,
    DropdownItem,
    NavbarText,
} from 'reactstrap';
import {checkAdminUser, checkLogin, getCurrentUser, logout} from '../auth'
import {context1} from '../context'

function CustomNavbar() {

    let navigate = useNavigate()
    const [isOpen, setIsOpen] = useState(false)

    const toggle = () => setIsOpen(!isOpen);

    const doLogout = () => {
        logout(() => {
            navigate("/")
        })
    }

    const htmlData = (value) => {
        return (

            < div>

                <Navbar
                    color='light'
                    fixed='top'
                    expand="md"
                    className='px-5 shadow-sm '
                >
                    <NavbarBrand tag={ReactLink} to="/">MyShop</NavbarBrand>
                    <NavbarToggler onClick={toggle}/>
                    <Collapse isOpen={isOpen} navbar>
                        <Nav className="me-auto" navbar>
                            <NavItem>
                                <NavLink tag={ReactLink} to="/store/all">Store</NavLink>
                            </NavItem>
                            <NavItem>
                                <NavLink tag={ReactLink} to="/services">
                                    Services
                                </NavLink>
                            </NavItem>
                            <NavItem>
                                <NavLink tag={ReactLink} to="/about">
                                    About
                                </NavLink>
                            </NavItem>
                            <UncontrolledDropdown nav inNavbar>
                                <DropdownToggle nav caret>
                                    Follow me
                                </DropdownToggle>
                                <DropdownMenu>
                                    <DropdownItem>Facebook</DropdownItem>
                                    <DropdownItem>Instagram</DropdownItem>
                                    <DropdownItem divider/>
                                    <DropdownItem>Youtube</DropdownItem>
                                    <DropdownItem>LinkedIn</DropdownItem>
                                </DropdownMenu>
                            </UncontrolledDropdown>
                        </Nav>
                        <Nav navbar>
                            <NavItem>
                                <NavLink tag={ReactLink} to="/user/cart">
                                    Cart ( <b>{value.cart.items.length}</b> )
                                </NavLink>
                            </NavItem>

                            {
                                (!checkLogin()) && (
                                    <>                                    <NavItem>
                                        <NavLink tag={ReactLink} to="/login">
                                            Login
                                        </NavLink>
                                    </NavItem>
                                        <NavItem>
                                            <NavLink tag={ReactLink} to="/singup">
                                                Singup

                                            </NavLink>
                                        </NavItem>

                                    </>
                                )
                            }


                            {
                                (checkLogin()) && (
                                    <>


                                        {
                                            (checkAdminUser() && (
                                                <NavItem>
                                                    <NavLink tag={ReactLink} to="/admin-dashboard/home">
                                                        Admin Dashboard
                                                    </NavLink>
                                                </NavItem>
                                            ))
                                        }

                                        <NavItem>
                                            <NavLink tag={ReactLink} to="/user/orders">
                                                Orders
                                            </NavLink>
                                        </NavItem>
                                        <NavItem>
                                            <NavLink tag={ReactLink} to="/user/dashboard">
                                                {getCurrentUser().name}
                                            </NavLink>
                                        </NavItem>
                                        <NavItem>
                                            <NavLink onClick={doLogout}>
                                                Logout
                                            </NavLink>
                                        </NavItem>

                                    </>
                                )
                            }

                        </Nav>
                    </Collapse>
                </Navbar>
            </div>
        )
    }

    return (
        <context1.Consumer>
            {
                (value) => htmlData(value)

            }
        </context1.Consumer>
    );

}

export default CustomNavbar

// angular-ecom/src/app/components/custom-navbar/custom-navbar.component.ts
import {Component, OnInit} from '@angular/core';
import {AuthHelperService} from 'src/app/services/auth-helper.service';
import {CartService} from 'src/app/services/cart.service';

@Component({
  selector: 'app-custom-navbar',
  templateUrl: './custom-navbar.component.html',
  styleUrls: ['./custom-navbar.component.css']
})
export class CustomNavbarComponent implements OnInit {


  isLogin = false;
  user: any = null
  cart: any
  adminUser = false

  constructor(
    private authHelper: AuthHelperService,
    private cartService: CartService
  ) {
  }

  ngOnInit(): void {


    this.cartService.cartEmitter.subscribe((cart: any) => {
      console.log(cart);
      this.cart = cart

    })

    this.updateLoginDetails()
    this.authHelper.loginLogoutEmitter.subscribe(value => {
      this.updateLoginDetails();
    })

  }

  updateLoginDetails() {
    this.adminUser = this.authHelper.checkAdminUser()
    this.isLogin = this.authHelper.checkLogin()
    this.user = this.isLogin ? this.authHelper.getCurrentUser() : null

  }


  logoutUser() {
    this.authHelper.logout()
  }

}

<nav class="navbar sticky-top navbar-expand-lg bg-light shadow-sm">
  <div class="container">
    <a class="navbar-brand"  routerLink="/home">MyShop</a>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" routerLink="/store/all">Store</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" routerLink="/services">Services</a>
        </li>
        <!--

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li> -->
        <li class="nav-item">
          <a class="nav-link" routerLink="/about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link">Contact Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink="/cart">Cart ( <b>{{ cart ? cart.items.length:0 }}</b> )</a>
        </li>
      </ul>

      <ul class="navbar-nav" *ngIf="!isLogin">
        <li class="nav-item">
          <a class="nav-link" routerLink="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink="/signup">Singup</a>
        </li>
      </ul>
      <ul class="navbar-nav" *ngIf="isLogin">
        <li class="nav-item" *ngIf="adminUser">
          <a class="nav-link" routerLink="/admin-dashboard">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink="/orders">Orders</a>
        </li>


        <li class="nav-item">
          <a class="nav-link" routerLink="/dashboard">{{user.name}}</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" (click)="logoutUser()" >Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
