// angular-ecom/src/app/pages/admin/add-product/add-product.component.ts
import { Component, OnInit } from '@angular/core';
import { ToastrService } from 'ngx-toastr';
import { CategoryService } from '../../../services/category.service'
import { Product } from 'src/app/models/Product';
import { ProductService } from 'src/app/services/product.service';
@Component({
  selector: 'app-add-product',
  templateUrl: './add-product.component.html',
  styleUrls: ['./add-product.component.css']
})
export class AddProductComponent implements OnInit {

  product = new Product('', '', 0, 0, true, true, '', 0)


  categories: any;

  constructor(
    private categoryService: CategoryService,
    private toast: ToastrService,
    private productService: ProductService
  ) { }

  ngOnInit(): void {

    this.getCategories();

  }

  getCategories() {
    this.categoryService.loadCategories().subscribe({
      next: data => {
        this.categories = data
        console.log(this.categories);

      },
      error: error => {
        console.log(error);
        alert("error in loading categories")

      }
    })
  }

  //submit the product
  submitProduct(event: Event) {
    event.preventDefault()
    console.log(this.product);

    // check the product details 
    if (this.product.getProductName().trim() === '') {
      this.toast.error("Product Name is required !!")
      return
    }

    if (this.product.getProductDesc().trim() === '') {
      this.toast.error("Product description is required !!")
      return
    }
    if (this.product.getProductPrice() <= 0) {
      this.toast.error("Invalid price !!")
      return
    }
    if (this.product.getProductQuantity() <= 0) {
      this.toast.error("Invalid price !!")
      return
    }

    if (this.product.getCategoryId() === 0) {
      this.toast.error("Must Select category !!")
      return
    }


    //create product api call
    this.productService.createProduct(this.product).subscribe({
      next: data => {
        console.log("Created Product");
        console.log(data)
        this.toast.success("Product is created")
        this.product = new Product('', '', 0, 0, true, true, '', 0)

      },
      error: error => {
        console.log(error);

        if (error.status == 403) {
          this.toast.error("you dont have enough permission to perform this operation")
        } else {
          this.toast.error("Error in creating product")
        }

      }
    })


  }

}



<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card border-0 shadow-sm">
        <div class="card-header">
          <h3 class="">Add New Product here</h3>
        </div>
        <div class="card-body">
          <form action="#" (ngSubmit)="submitProduct($event)">
            <div class="my-3">
              <label for="productName">Product name</label>
              <input
                id="productName"
                type="text"
                class="form-control"
                placeholder="Enter product title"
                [(ngModel)]="product.productName"
                name="productName"
              />
            </div>
            <div class="my-3">
              <label for="productName">Product name</label>
              <textarea
                style="height: 250px"
                class="form-control"
                placeholder="Enter product here"
                [(ngModel)]="product.productDesc"
                name="productDesc"
              ></textarea>
            </div>

            <div class="my-3">
              <label for="productName">Product price</label>
              <input
                id="productName"
                type="text"
                class="form-control"
                placeholder="Enter product price"
                [(ngModel)]="product.productPrice"
                name="productPrice"
              />
            </div>
            <div class="my-3">
              <label for="productQuantity">Product Quantity</label>
              <input
                id="productQuantity"
                type="text"
                class="form-control"
                placeholder="Enter product qantity"
                [(ngModel)]="product.productQuantity"
                name="productQuantity"
              />
            </div>

            <div class="form-group form-check mx-2">
              <input
                type="checkbox"
                class="form-check-input"
                [(ngModel)]="product.live"
                id="live"
                name="live"
              />
              <label class="form-check-label" for="live">Live</label>
            </div>
            <div class="form-group form-check mx-2">
              <input
                type="checkbox"
                class="form-check-input"
                [(ngModel)]="product.stock"
                id="stock"
                name="stock"
              />
              <label class="form-check-label" for="stock"
                >Product is in stock</label
              >
            </div>

            <div class="form-group my-3">
              <label for="file">Choose Product banner</label>
              <br />
              <input type="file" class="form-control-file" id="file" />
            </div>

            <div class="form-group">
              <label for="category">Select Category</label>
              <select
                [(ngModel)]="product.categoryId"
                name="category"
                id="category"
                class="form-control"
                name="category"
              >
                <option [value]="c.categoryId" *ngFor="let c of categories">
                  {{ c.title }}
                </option>
              </select>
            </div>

            <div class="container text-center mt-3">
              <button type="submit" class="btn-success btn">Add Product</button>
              <button type="reset" class="btn-warning btn ms-2">
                Reset Product Detail
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

// react-ecom/src/pages/admin/AddProduct.jsx
import React, {useEffect, useState} from 'react'
import {Button, Card, CardBody, Col, Container, Form, FormGroup, Input, Label, Row} from "reactstrap";
import {loadCategories} from "../../services/category-serivce";
import {toast} from "react-toastify";
import {addProduct} from "../../services/product-service";

function AddProduct() {

    const [categories, setCategories] = useState([])

    const [product, setProduct] = useState({
        productName: '',
        productDesc: '',
        productPrice: 0,
        productQuantity: 0,
        live: true,
        stock: true,
        imageName: '',
        categoryId: 0

    });

    useEffect(() => {

        loadCategories().then(cats => {
            setCategories([...cats])
        })
            .catch(error => {
                console.log(error)
                toast.error("error in loading categories")
            })

    }, []);

    function addProductFormSubmit(event) {

        event.preventDefault()
        addProduct(product).then(data => {
            console.log(data)
            toast.success("Product added success")
            setProduct({
                productName: '',
                productDesc: '',
                productPrice: 0,
                productQuantity: 0,
                live: true,
                stock: true,
                imageName: '',
                categoryId: 0

            })
        }).catch(error => {
            console.log(error)
            toast.error("error in adding product")
        })
    }

    function addProductHtml() {
        return (
            <Row>
                <Col>

                    <h3>Add New Product</h3>

                    <Form onSubmit={addProductFormSubmit}>


                        {/*name*/}

                        <FormGroup>
                            <Label>Product name</Label>
                            <Input type={'text'}
                                   value={product.productName}
                                   onChange={event => setProduct({...product, productName: event.target.value})}
                            />
                        </FormGroup>


                        {/*description*/}

                        <FormGroup>
                            <Label>Product description</Label>
                            <Input type={'textarea'}
                                   value={product.productDesc}
                                   onChange={event => setProduct({...product, productDesc: event.target.value})}

                            />
                        </FormGroup>


                        {/*price*/}

                        <FormGroup>
                            <Label>Product price</Label>
                            <Input type={'number'}
                                   value={product.productPrice}
                                   onChange={event => setProduct({...product, productPrice: event.target.value})}

                            />

                        </FormGroup>

                        {/*quantity*/}

                        <FormGroup>
                            <Label>Product quantity</Label>
                            <Input type={'number'}
                                   value={product.productQuantity}
                                   onChange={event => setProduct({...product, productQuantity: event.target.value})}

                            />
                        </FormGroup>


                        {/*live*/}

                        <FormGroup>
                            <Label for={'live'}>Product Live</Label>
                            <Input className={'ms-2'} id={'live'} type={"checkbox"}
                                   checked={product.live}

                                   onChange={event => setProduct({...product, live: !product.live})}

                            />
                        </FormGroup>
                        {/*stock*/}

                        <FormGroup>
                            <Label for={'stock'}>Product stock</Label>
                            <Input className={'ms-2'} id={'stock'} type={"checkbox"}
                                   checked={product.stock}
                                   onChange={event => setProduct({...product, stock: !product.stock})}

                            />
                        </FormGroup>

                        {/*image*/}

                        <FormGroup>
                            <Label for={'image'}>Product Banner</Label>
                            <Input className={'ms-2'} id={'image'} type={"file"}/>
                        </FormGroup>

                        {/*    product category*/}

                        <FormGroup>
                            <Label for={'image'}>Product Banner</Label>
                            <Input className={'ms-2'} id={'image'} type={"select"}
                                   value={product.categoryId}
                                   onChange={event => setProduct({...product, categoryId: event.target.value})}

                            >
                                {
                                    categories.map((cat, i) => {
                                        return (
                                            <option value={cat.categoryId} key={i}>{cat.title}</option>
                                        )
                                    })
                                }
                            </Input>
                        </FormGroup>

                        <Container className={'text-center'}>
                            <Button type={'submit'} color={'success'}>Add Product</Button>
                        </Container>

                    </Form>

                </Col>
            </Row>
        )
    }

    return (

        <Container>
            <Card>
                <CardBody>
                    {addProductHtml()}

                </CardBody>
            </Card>
        </Container>

    )
}

export default AddProduct
