// angular-ecom/src/app/pages/admin/manage-order/manage-order.component.ts
import {Component, OnInit} from '@angular/core';
import {CartService} from "../../../services/cart.service";
import {ToastrService} from "ngx-toastr";
import {NgbModal} from "@ng-bootstrap/ng-bootstrap";
import {environment} from "../../../../environments/environment";

@Component({
  selector: 'app-manage-order',
  templateUrl: './manage-order.component.html',
  styleUrls: ['./manage-order.component.css']
})
export class ManageOrderComponent implements OnInit {
  orders: any;
  baseUrl: string;

  constructor(
    private orderService: CartService,
    private toast: ToastrService,
    private modalService: NgbModal
  ) {

    this.baseUrl = environment.baseUrl
  }

  ngOnInit(): void {
    this.getOrders();
  }

  private getOrders() {
    this.orderService.getAllOrders().subscribe({
      next: data => {
        this.orders = data
        console.log(this.orders)
      },
      error: error => {
        console.log(error)

      }
    })
  }

  getDate(number: number) {
    return new Date(number).toDateString()
  }

  selectedOrder: any

  openModal(content: any, orderId: number) {

    this.selectedOrder = this.orders.find((order: any) => order.orderId == orderId)
    console.log(this.selectedOrder);

    this.modalService.open(content, {size: 'lg'})


  }

}

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <h3>All orders is here</h3>
          <div class="table-responsive">
            <table class="table">
              <thead>
              <tr>
                <th>
                  Order Id
                </th>
                <th>
                  Amount
                </th>
                <th>
                  Status
                </th>
                <th>
                  Payment
                </th>
                <th>
                  Created
                </th>
                <th>
                  Items
                </th>
                <th>Action</th>
              </tr>
              </thead>

              <tbody>
              <tr *ngFor="let o of orders">
                <td>{{o.orderId}}</td>
                <td>
                  {{o.orderAmount}}
                </td>
                <td>
                  {{o.orderStatus}}
                </td>
                <td>
                  {{o.paymentStatus}}
                </td>
                <td>{{getDate(o.orderCreated)}}</td>
                <td>{{o.items.length }} items</td>
                <td>
                  <button class="btn btn-warning btn-sm" (click)="openModal(content, o.orderId)">View</button>
                  <button class="btn btn-danger ms-2 btn-sm">Update</button>
                </td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- modal html  -->

<ng-template #content let-modal>
  <div class="modal-header">
    <h4 class="modal-title" id="modal-basic-title">Products</h4>
    <button
      type="button"
      class="btn-close"
      aria-label="Close"
      (click)="modal.dismiss('Cross click')"
    ></button>
  </div>
  <div class="modal-body">
    <div class="card border-0 mt-3 shadow-sm" *ngFor="let item of selectedOrder.items">
      <div class="card-body">
        <div class="row">
          <div class="col-md-8">
            <h5>{{ item.product.productName }}</h5>
            <div class="cart-text">
              Quantity : <b>{{ item.quantity }}</b>
            </div>

            <div class="cart-text">
              Price : <b> ₹ {{ item.totalProductPrice }}</b>
            </div>
          </div>

          <div class="col-md-4 text-center">
            <img
              [src]="baseUrl + '/products/images/' + item.product.productId"
              class="img-fluid product-img"
              alt=""
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</ng-template>

// react-ecom/src/pages/admin/ManageOrder.jsx
import React, {useEffect, useState} from 'react'
import {getAllOrders} from "../../services/order-service";
import {toast} from "react-toastify";
import {Button, Card, CardBody, Col, Container, Row, Table} from "reactstrap";

function ManageOrder() {
    const [orders, setOrders] = useState([]);
    useEffect(() => {
        getAllOrders().then(res => {
            console.log(res)
            toast.success("orders loaded")
            setOrders([...res])
        })
            .catch(error => {
                console.log(error)
                toast.error("error in loading orders")
            })
    }, [])

    function viewOrderHtml() {
        return (
            <Row>
                <Col md={12}>

                    <h1>All order is here</h1>
                    <Table>
                        <thead>
                        <tr>
                            <th>
                                OrderId
                            </th>
                            <th>
                                Amount
                            </th>
                            <th>
                                Status
                            </th>
                            <th>
                                Payment
                            </th>
                            <th>
                                Created
                            </th>
                            <th>
                                Items
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {
                            orders.map((order, i) => {
                                return (
                                    <tr key={i}>
                                        <td>
                                            {order.orderId}
                                        </td>

                                        <td>
                                            {order.orderAmount}
                                        </td>
                                        <td>
                                            {order.orderStatus}
                                        </td>
                                        <td>
                                            {order.paymentStatus}
                                        </td>
                                        <td>
                                            {new Date(order.orderCreated).toDateString()}
                                        </td>
                                        <td>
                                            {order.items.length} Items
                                        </td>
                                        <td>
                                            <Button color={'warning'}>View</Button>
                                        </td>
                                    </tr>
                                )
                            })
                        }
                        </tbody>
                    </Table>

                </Col>
            </Row>
        )
    }

    return (

        <Container>
            <Card>
                <CardBody>
                    {orders && viewOrderHtml()}
                </CardBody>
            </Card>
        </Container>
    )
}

export default ManageOrder
