// angular-ecom/src/app/components/cart/cart.component.ts
import {Component, Inject, OnInit, PLATFORM_ID} from '@angular/core';
import {ToastrService} from 'ngx-toastr';
import {CartService} from 'src/app/services/cart.service';
import {environment} from 'src/environments/environment';
import {PaymentService} from "../../services/payment.service";
import {isPlatformBrowser} from "@angular/common";
import {Router} from "@angular/router";
import {WindowRef} from "../../services/WindowRef";


@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.css']
})
export class CartComponent implements OnInit {
  cart: any;
  baseUrl = ''
  orderProceed = false
  order = {
    address: '',
    cartId: ''
  }

  redirect = false

  constructor(
    private cartService: CartService,
    private toast: ToastrService,
    private paymentService: PaymentService,
    private windowRef: WindowRef,
    private router: Router
  ) {

    this.baseUrl = environment.baseUrl
  }

  ngOnInit(): void {
    this.loadCart()
  }

  loadCart() {

    this.cartService.getCart().subscribe(
      {
        next: data => {
          console.log(data);
          this.cart = data
          this.cartService.cartChanged(this.cart)


        },
        error: error => {
          console.log(error)
        }
      }
    )

  }

  removeItem(item: any) {
    this.cartService.removeItemFromCart(item.product.productId).subscribe({
      next: data => {
        console.log(data);
        this.cart = data
        this.toast.success("Item is removed from cart")
        this.cartService.cartChanged(this.cart)
      },
      error: error => {
        console.log(error);
        this.toast.error(error.error)

      }
    })
  }

  quantityChange(productId: any, quantity: any) {
    this.cartService.addItemToCart(productId, quantity).subscribe({
      next: data => {
        console.log(data);
        this.cart = data
        this.toast.success("Quantity Changes")
        this.cartService.cartChanged(this.cart)
      },
      error: error => {
        console.log(error);

      }
    })
  }

  //createOrderAndProceedForPayment
  createOrderAndProceedForPayment() {

    this.order.cartId = this.cart.cartId
    console.log(this.order);

    this.cartService.createOrder(this.order).subscribe({
      next: (data: any) => {
        console.log(data);
        this.toast.success("Order Created")
        this.loadCart()
        this.toast.success("Redirecting to payment page")
        this.redirect = true
        this.startPaymentComponent(data.orderAmount, data);

      },
      error: (error) => {
        console.log(error);
        this.toast.error("Error in creating order")

      }
    })

  }

  private startPaymentComponent(number: number, userOrder: any) {
    this.paymentService.startPayment(number).subscribe({
      next: (data: any) => {
        console.log(data)
        // this.toast.success("Order Created For payment")
        // open the form

        if (data.message === 'CREATED') {
          let options: any = {
            "key": "rzp_test_Hp2rdy1ivO3J3p", // Enter the Key ID generated from the Dashboard
            "amount": data.price, // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
            "currency": "INR",
            "name": "LCWD Payment",
            "description": "This is ecommerce payment",
            "image": "https://learncodewithdurgesh.com/_next/image?url=%2Fimages%2Fdurgesh_sir.webp&w=1920&q=75",
            "order_id": data.orderId, //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
            "callback_url": "https://learncodewithdurgesh.com",
            "prefill": {
              "name": "",
              "email": "",
              "contact": ""
            },
            "notes": {
              "address": ""
            },
            "theme": {
              "color": "#3399cc"
            }
          };


          options.handler = (response: any) => {

            response['user_order_id'] = userOrder.orderId;

            console.log(response)


            this.paymentService.successPayment(response).subscribe({
              next: (res: any) => {
                console.log(res)
                if (res.captured) {
                  this.router.navigate(['/orders'])
                  this.toast.success("Payment done : We are forwarding your order.")
                }


              }
            })


          }


          const rzp = new this.windowRef.nativeWindow.Razorpay(options);
          rzp.open()

        }


      },
      error: error => {
        console.log(error)
        this.toast.error("Error in creating order for payment")
      }
    })
  }


}

<div *ngIf="!orderProceed">
    <div class="container" *ngIf="cart">
        <div class="row mt-2">
         <div class="col-md-12">
             <h1>Cart Items ( {{cart.items.length}} )</h1>
     
             <br>
     
             <div class="card mt-2 border-0" *ngFor="let item of cart.items">
                 <div class="card-body">
                    <div class="row">
                     <div class="col-md-8">
                         <h5>{{item.product.productName}}</h5>
                         <div class="cart-text">
                             Quantity : <b>{{item.quantity}}</b>
         
                         </div>
                         <div class="container-fluid ps-0 py-3">
                             <button (click)="quantityChange(item.product.productId,(item.quantity+1))" class="btn btn-primary btn-sm">Increase Quantity</button>
                             <button (click)="quantityChange(item.product.productId,(item.quantity-1))" class="btn btn-dark ms-2 btn-sm">Decrease Quantity</button>
                             <button (click)="removeItem(item)" class="btn btn-danger ms-2 btn-sm">Remove Item</button>
                         </div>
                         <div class="cart-text">
                             Price  : <b> ₹ {{item.totalProductPrice}}</b>
         
                         </div>
                     </div>
     
                     <div class="col-md-4 text-center">
                        <img  [src]="baseUrl+'/products/images/'+item.product.productId"  class="img-fluid product-img" alt="">
                     </div>
                    </div>
                 </div>
             </div>
     
     
             <div class="container mt-3 border-0 text-center" *ngIf="cart.items.length>0">
                 <button (click)="orderProceed=true" class="btn btn-success btn-lg">Click to proceed</button>
             </div>
     
         </div>
        </div>
     </div>
</div>
<div *ngIf="orderProceed && !redirect" class="mt-4">

    <div class="container">
       <div class="row">
        <div class="col-md-12">
            <h1>Enter shipping added with pin code</h1>
            <div class="form-goup mt-3">
                <textarea [(ngModel)]="order.address" name="" id="" placeholder="Enter you address here" rows="10" class="form-control"></textarea>
            </div>
            <p class="p-2 text-danger">We will use your profile contact number to contact you. for any query drop a mail <b>learncodewithdurgesh@gmail.com.</b> </p>
           
        </div>
        <div class="container text-center">
            <button (click)="createOrderAndProceedForPayment()" class="btn btn-success btn-lg">Proceed for payment</button>
        </div>
       </div>
    </div>

</div>

<div class="container mt-3" *ngIf="redirect">
   <h1> Readirecting to payment page.....</h1>
</div>

// react-ecom/src/components/Cart.jsx
import React from 'react'
import {useState} from 'react'
import {useContext} from 'react'
import {useEffect} from 'react'
import {toast} from 'react-toastify'
import {CardBody, Container, Card, CardText, Button, FormGroup, Input, Col, Row} from 'reactstrap'
import {context1} from '../context'
import {addItemToCart, getCart, removeItemFromCart as removeItem} from '../services/cart-service'
import Base from './Base'
import {BASE_URL} from '../services/axios-helper'
import {createOrder as createOrderService} from '../services/order-service'
import {createOrder as paymentOrder, successPayment} from '../services/payment.service'
import {useNavigate} from "react-router-dom";

function Cart() {

    const navigate=useNavigate()

    let imageStyle = {
        width: '100%',
        height: '100px',
        objectFit: 'contain',
        margin: '15px 0'
    }

    const value = useContext(context1)
    const [cart, setCart] = useState(null)
    const [orderProceed, setOrderProceed] = useState(false)
    const [orderDetail, setOrderDetail] = useState({
        address: '',
        cartId: ''
    })
    const [orderCreated, setOrderCreated] = useState(false)

    useEffect(() => {


        getCart().then(data => {
            setCart(data)
            value.setCart(data)
            console.log(data)
        }).catch(error => {
            console.log(error)
        })

    }, [])

    const changeQuantity = (productId, quantity) => {
        addItemToCart(productId, quantity)
            .then(
                data => {
                    setCart({...data})
                }
            )
            .catch(error => {
                console.log(error)
                toast.error("Error in changing the quantity")
            })
    }

    const removeItemFromCart = (item) => {
        removeItem(item.product.productId).then(data => {
            setCart(data)
            value.setCart(data)
        }).catch(error => {
            console.log(error)
        })
    }

    const initializeRazorpay = () => {
        return new Promise((res) => {
            const script = document.createElement("script")
            script.src = 'https://checkout.razorpay.com/v1/checkout.js'

            script.onload = () => {
                res(true)
            }

            script.onerror = () => {
                res(false)
            }

            document.body.appendChild(script)
        })

    }

    //initiate payment
    async function initiatePayment(data) {

        const res = await initializeRazorpay();
        if (res) {
            //console.log("Razorpayintialized")
            paymentOrder(data.orderAmount).then(res => {
                console.log(res)
                toast.success("order created")
                if (res.message === 'CREATED') {


                    //open payment form


                    var options = {
                        "key": "rzp_test_I1W91GjgtQTy1J", // Enter the Key ID generated from the Dashboard
                        "amount": res.price, // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
                        "currency": "INR",
                        "name": "LCWD Payment Page",
                        "description": "This is learning payment module",
                        "image": "https://learncodewithdurgesh.com/_next/image?url=%2Fimages%2Fdurgesh_sir.webp&w=1920&q=75",
                        "order_id": res.orderId, //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
                        "prefill": {
                            "name": "",
                            "email": "",
                            "contact": "9999999999"
                        },
                        "notes": {
                            "address": ""
                        },
                        "theme": {
                            "color": "#3399cc"
                        }
                    };


                    options.handler = (response) => {


                        response['user_order_id'] = data.orderId
                        console.log(response)

                        successPayment(response).then(r => {
                            console.log(r)
                            if (r.captured) {
                                toast.success("Payment done .. your order proceeded")
                                navigate("/user/orders")

                            }

                        }).catch(error => {
                            console.log(error)
                            toast.error("Error while capturing the payment :")
                        })


                    }


                    const rzp = new window.Razorpay(options);
                    rzp.open()


                }

            }).catch(error => {
                console.log(error)
                toast.error("Error in creating order")
            })


        } else {
            toast.error("Error in initializing razorpay")
        }

    }

    const createOrder = () => {
        let f = window.confirm("Are you sure want to proceed ?")

        if (f === false) {
            console.log(f)
            return;
        }
        //updating the cart id of order detail
        orderDetail.cartId = cart.cartId
        createOrderService(orderDetail).then((data) => {

            console.log(data)
            toast.success("Order Created : Redirecting to payment page... ")
            setOrderCreated(true)

            initiatePayment(data);
        })
            .catch(error => {
                console.log(error)
                toast.error("Error in creating order")


            })
    }


    const cartItemsHtml = () => {
        return (<div className='mt-3'>
            {cart.items.map((item, index) => (
                <Card className="mt-2 border-0 shadow-sm" key={index}>
                    <CardBody>
                        <Row>
                            <Col md={8}>
                                <h3>{item.product.productName}</h3>
                                <CardText>
                                    Quantity : <b>{item.quantity}</b>
                                </CardText>
                                <div>
                                    <Button color='primary'
                                            onClick={() => changeQuantity(item.product.productId, (item.quantity + 1))}
                                            className=' border-0 border rounded-0' size='sm'>Increase Quantity</Button>
                                    <Button color='warning'
                                            onClick={() => changeQuantity(item.product.productId, (item.quantity - 1))}
                                            className='ms-2 border-0 border rounded-0' size='sm'>Decrease
                                        Quantity</Button>
                                    <Button onClick={(event) => {
                                        removeItemFromCart(item)
                                    }} color='danger' className='ms-2 border-0 border rounded-0' size='sm'>Remove
                                        Item</Button>
                                </div>

                                <CardText className='mt-3'>
                                    Total Price : <b>{item.totalProductPrice}</b>
                                </CardText>

                            </Col>
                            <Col md={4}>
                                <img style={imageStyle} src={BASE_URL + '/products/images/' + item.product.productId}
                                     alt=""/>

                            </Col>
                        </Row>
                    </CardBody>
                </Card>
            ))}

            <Container className='my-3 text-center'>
                {cart.items.length > 0 ? (
                    <Button onClick={() => setOrderProceed(true)} color='success' size='lg'>Click here to
                        proceed</Button>) : ''}
            </Container>


        </div>)
    }


    const cartHtml = () => {
        return (
            <Container>
                <h1>Cart Items ( {cart.items.length} )</h1>

                {orderProceed ? orderCreated ?
                    <h1>Order Created , Redirecting to payment page ..</h1> : orderProceedHtml() : cartItemsHtml()}
            </Container>
        )
    }


    const orderProceedHtml = () => {
        return (
            <div>
                <h1>Fill the detail :</h1>

                <FormGroup>
                    <Input style={{
                        height: '300px'
                    }} type='textarea' value={orderDetail.address}
                           onChange={(event) => setOrderDetail({...orderDetail, address: event.target.value})}
                           placeholder='Enter your addess here'/>
                </FormGroup>

                <Container className='text-center'>
                    <Button onClick={() => setOrderProceed(false)} color='secondary' size='lg'>Back</Button>
                    <Button onClick={createOrder} color='success' className='ms-2' size='lg'>Create Order & Proceed for
                        Payment</Button>
                </Container>

            </div>
        )
    }

    return (
        <Base>
            {cart ? cartHtml() : (
                <Container>
                    <h1>Loading .....</h1>
                </Container>
            )}
        </Base>
    )
}

export default Cart
