// angular-ecom/src/app/components/orders/orders.component.ts
import { Component, ElementRef, OnInit } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { ToastrService } from 'ngx-toastr';
import { CartService } from 'src/app/services/cart.service';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-orders',
  templateUrl: './orders.component.html',
  styleUrls: ['./orders.component.css']
})
export class OrdersComponent implements OnInit {

  orders: any;
  baseUrl:any

  constructor(
    private cartService: CartService,
    private toast: ToastrService,
    private modalService: NgbModal
  ) { 

    this.baseUrl=environment.baseUrl
  }



  ngOnInit(): void {

    this.loadOrders()

  }

  loadOrders() {

    this.cartService.getOrders().subscribe({
      next: (data) => {
        console.log(data);
        this.toast.success("Order loaded")
        this.orders = data
      },
      error: error => {
        console.log(error);
        this.toast.error("Error in loading orders")

      }
    })

  }

  getFormattedDate(time: number) {
    return new Date(time).toDateString()
  }

  selectedOrder: any
  openModal(content: any, orderId: number) {

    this.selectedOrder = this.orders.find((order: any) => order.orderId == orderId)
    console.log(this.selectedOrder);

    this.modalService.open(content, { size: 'lg' })


  }

}

<div class="container">
  <div class="row mt-2" *ngIf="orders">
    <div class="col-md-12">
      <h1>Orders ( {{ orders.length }} )</h1>

      <div
        class="card mt-2 shadow-sm border-3"
        [ngClass]="
          order.paymentStatus == 'NOT PAID' ? 'border-danger' : 'border-success'
        "
        *ngFor="let order of orders"
      >
        <div class="card-body">
          <div class="row mt-2">
            <div class="col-md-6">
              <div class="card-text">
                ORDER NUMBER : <b>MYSHOP{{ order.orderId }}</b>
              </div>
            </div>
            <div class="col-md-6">
              CREATED AT : <b>{{ getFormattedDate(order.orderCreated) }} </b>
            </div>
          </div>
          <div class="row mt-2">
            <div class="col-md-6">
              <div class="card-text">
                ORDER STATUS : <b>{{ order.orderStatus }}</b>
              </div>
            </div>
            <div class="col-md-6">
              AMOUNT : ₹ <b>{{ order.orderAmount }} </b>
            </div>
          </div>
          <div class="row mt-2">
            <div class="col-md-6">
              <div class="card-text">
                PAYMENT STATUS : <b>{{ order.paymentStatus }}</b>
              </div>
            </div>
            <div class="col-md-6">
              ORDER DELIVERED:
              <b>{{
                order.orderDelivered ? order.orderDelivered : "NOT DELIVERED"
              }}</b>
            </div>
          </div>

          <div class="cart-text">
            {{ order.billingAddress }}
          </div>
        </div>
        <div class="card-footer text-center">
          <button
            class="btn btn-primary btn-sm"
            (click)="openModal(content, order.orderId)"
          >
            View Products
          </button>
          <button
            class="btn btn-success ms-2 btn-sm"
            *ngIf="order.paymentStatus == 'NOT PAID'"
          >
            Pay to Process
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- modal html  -->

<ng-template #content let-modal>
  <div class="modal-header">
    <h4 class="modal-title" id="modal-basic-title">Products</h4>
    <button
      type="button"
      class="btn-close"
      aria-label="Close"
      (click)="modal.dismiss('Cross click')"
    ></button>
  </div>
  <div class="modal-body">
    <div class="card border-0 mt-3 shadow-sm" *ngFor="let item of selectedOrder.items">
      <div class="card-body">
        <div class="row">
          <div class="col-md-8">
            <h5>{{ item.product.productName }}</h5>
            <div class="cart-text">
              Quantity : <b>{{ item.quantity }}</b>
            </div>

            <div class="cart-text">
              Price : <b> ₹ {{ item.totalProductPrice }}</b>
            </div>
          </div>

          <div class="col-md-4 text-center">
            <img
              [src]="baseUrl + '/products/images/' + item.product.productId"
              class="img-fluid product-img"
              alt=""
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</ng-template>

// react-ecom/src/components/Orders.jsx
import React, { useEffect } from 'react'
import { useState } from 'react'
import { toast } from 'react-toastify'
import { Button, Card, CardBody, CardText, Col, Container, Row, Modal, ModalHeader, ModalBody, ModalFooter } from 'reactstrap'
import { getOrders } from '../services/order-service'
import Base from './Base'
import { BASE_URL } from '../services/axios-helper'

function Orders() {


  let imageStyle = {
    width: '100%',
    height: '100px',
    objectFit: 'contain',
    margin: '15px 0'
  }

  const [orders, setOrders] = useState(null)
  const [modal, setModal] = useState(false);
  const [selectedItem, setSelectedItem] = useState(null)

  const closeModal = () => setModal(false);
  const openModal = (order) => {
    setSelectedItem(order)
    setModal(true)
  };


  useEffect(() => {

    getOrders().then(data => {
      console.log(data)
      setOrders([...data])
    }).catch(error => {
      console.log(error)
      toast.error("Error in loading orders")
    })

  }, [])




  const formatDate = (time) => {
    return new Date(time).toDateString()
  }



  const modalHtml = () => {
    return (
      <Modal isOpen={modal} toggle={closeModal} size='lg' centered={true} >
        <ModalHeader toggle={closeModal}>Products of order {selectedItem && 'MYSHOP'+selectedItem.orderId}</ModalHeader>
        <ModalBody>

          {
            selectedItem && selectedItem.items.map((item, index) => (
              <Card className="mt-2 border-0 shadow-sm" >
                <CardBody>

                  <Row key={index}>
                    <Col md={8}>
                      <h3>{item.product.productName}</h3>
                      <CardText>
                        Quantity : <b>{item.quantity}</b>
                      </CardText>


                      <CardText className='mt-3'>
                        Total Price : <b>{item.totalProductPrice}</b>
                      </CardText>

                    </Col>
                    <Col md={4}>
                      <img style={imageStyle} src={BASE_URL + '/products/images/' + item.product.productId} alt="" />

                    </Col>
                  </Row>

                </CardBody>
              </Card>
            ))
          }


        </ModalBody>
      
      </Modal>
    )
  }

  const htmlCode = () => {
    return (<Row>

      <Col md={{ size: 8, offset: 2 }} >

        {orders.map((order) => (
          <Card className={order.paymentStatus == 'PAID' ? 'border-success mt-2' : 'border-danger mt-2'} key={order.orderId} >
            <CardBody>

              <Row className="mt-2">
                <Col md={6}>

                  <CardText>
                    ORDER NUMBER : <b> MYSHOP{order.orderId}</b>
                  </CardText>
                </Col>
                <Col md={6}>
                  CREATED AT: <b>{formatDate(order.orderCreated)}</b>
                </Col>
              </Row>
              <Row className="mt-2">
                <Col md={6}>

                  <CardText>
                    ORDER STATUS : <b> {order.orderStatus}</b>
                  </CardText>
                </Col>
                <Col md={6}>
                  ORDER AMOUNT: <b>₹ {order.orderAmount}</b>
                </Col>
              </Row>
              <Row className="mt-2">
                <Col md={6}>

                  <CardText>
                    PAYMENT STATUS : <b className={order.paymentStatus == 'PAID' ? 'text-success' : 'text-danger'}> {order.paymentStatus}</b>
                  </CardText>
                </Col>
                <Col md={6}>
                  ORDER DELIVERED: <b>{order.orderDelivered ? formatDate(order.orderDelivered) : 'Not delivered yet'}</b>
                </Col>
              </Row>

              <CardText className='mt-2 text-muted'>
                {order.billingAddress}
              </CardText>

              <Container className='text-center'>

                {order.paymentStatus == 'NOT PAID' ? <Button color='success' className='border-0' size='sm'>Pay Now</Button> : ''}
                <Button color='primary' size='sm' className='ms-2' onClick={() => openModal(order)}>View Products</Button>
              </Container>


            </CardBody>


          </Card>
        ))
        }

      </Col>
    </Row>
    )
  }

  return (
    <Base>
      <Container>
        {orders ? htmlCode() : <h1>Loading .....</h1>}
      </Container>
      {modalHtml()}
    </Base>


  )
}

export default Orders
