// angular-ecom/src/app/components/product/product.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css']
})
export class ProductComponent implements OnInit {

  @Input() product: any

  baseUrl: string = ''
  constructor() {
    this.baseUrl = environment.baseUrl
  }

  ngOnInit(): void {
  }

}

<div class="card mt-2 border-0 shadow-sm" *ngIf="product">

    <img  [src]="baseUrl+'/products/images/'+product.productId" class="card-img-top  product-img" alt="">


    <div class="card-body border border-top-1">
        <div class="card-text mb-3">
            <span class="text-muted">
                {{product.category.title}}
            </span>
        </div>
        <h5>{{product.productName}}</h5>
        <div class="card-text">
            <p>{{product.productDesc | slice: 0: 25 }}....</p>
        </div>
        <div class="divider"></div>

        <div class="mt-2">
            Price : <span class="fw-bold">₹ {{product.productPrice}} </span>
        </div>
        <div class="fuild-container mt-2 text-center">
            <button class="btn btn-success btn-sm">Add to Card</button>
            <button class="btn btn-primary btn-sm ms-1">View Product</button>
        </div>

    </div>
</div>

// react-ecom/src/components/Product.jsx
import React from 'react'
import { Button, Card, CardBody, CardText, Container } from 'reactstrap'
import { BASE_URL } from '../services/axios-helper'

function Product({ product }) {

    let imageStyle = {
        width: '100%',
        height: '200px',
        objectFit: 'contain',
        margin: '15px 0'
    }

    const getProductHtml = ()=>{
        return(
            <Card className='mt-2 border-0 shadow-sm' >

                <img style={imageStyle} src={BASE_URL+'/products/images/'+product.productId} alt="" />

                <CardBody>

                    <CardText><span className="text-mutted">{product.category.title}</span></CardText>

                    <h5>{product.productName}</h5>
                    <CardText>
                        <span>{product.productDesc.slice(0,20)}....</span>
                    </CardText>

                    <CardText>
                        Price : <b>₹ {product.productPrice}</b>
                    </CardText>

                    <Container className='text-center'>
                        <Button size='sm' color='success' >Add to Cart</Button>
                        <Button size='sm' className='ms-2' color='danger' >View Product</Button>
                    </Container>

                </CardBody>

            </Card>
        )
    }

    return (

        (product) && getProductHtml()

    )
}

export default Product
