// angular-ecom/src/app/components/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { UserService } from 'src/app/services/user.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {

  user = {
    name: '',
    email: '',
    password: '',
    address: '',
    about: '',
    phone: '',
    gender: ''
  }

  constructor(private userService: UserService) { }

  ngOnInit(): void {
  }

  //submit the form
  submitForm(event: any) {

    event.preventDefault();
    console.log(this.user);
    if (this.user.name.trim() === '') {
      alert("username is blank!!")
      return;
    } else if (this.user.email.trim() === '') {
      alert("email is blank !!")
      return;

    }

    //form submit
    this.userService.createUser(this.user).subscribe(
      (success) => {
        console.log(success);
        alert("user is registered successfully !! ")

      }, (error) => {
        console.log(error);
        if(error.status==400){
          alert("validation error")
        }

      }
    )

  }

}

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <!-- //main content area  -->
      <div class="card border-0 shadow-sm mt-5">
        <div class="card-body">
          <h3>Signup Here</h3>
          <div class="card-title">Fill the correct details</div>
          <form action="#" (ngSubmit)="submitForm($event)" novalidate>
            <!-- name field  -->
            <div class="mb-2 mt-4">
              <label for="name">Your name</label>
              <input
                type="text"
                required
                id="name"
                name="name"
                [(ngModel)]="user.name"
                class="form-control rounded-0"
                placeholder="Enter here"
              />
            </div>
            <!-- email field  -->
            <div class="mb-2">
              <label for="email">Your email</label>
              <input
                type="email"
                required
                name="email"
                id="email"
                [(ngModel)]="user.email"
                class="form-control rounded-0"
                placeholder="Enter here"
              />
            </div>
            <!-- password field  -->
            <div class="mb-2">
              <label for="password">Your password</label>
              <input
                type="password"
                required
                name="password"
                id="password"
                [(ngModel)]="user.password"
                class="form-control rounded-0"
                placeholder="Enter here"
              />
            </div>

            <!-- about field  -->

            <div class="mb-2">
              <label for="about">Something about yourself</label>
              <textarea
                style="height: 100px"
                name="about"
                
                [(ngModel)]="user.about"
                class="form-control rounded-0"
                id="about"
              ></textarea>
            </div>

            <!-- address field  -->
            <div class="mb-2">
              <label for="address">Address</label>
              <textarea
                style="height: 50px"
                name="address"
                class="form-control rounded-0"
                id="address"
                [(ngModel)]="user.address"
              ></textarea>
            </div>

            <!-- gender field  -->
            <div class="mb-2">
              <div class="form-check form-check-inline">
                <input
                  type="radio"
                  name="gender"
                  class="form-check-input"
                  id="female"
                  [(ngModel)]="user.gender"
                  value="female"
                />
                <label class="form-check-label" for="female">Female</label>
              </div>
              <div class="form-check form-check-inline">
                <input
                  type="radio"
                  name="gender"
                  class="form-check-input"
                  id="male"
                  [(ngModel)]="user.gender"
                  value="male"
                />
                <label class="form-check-label" for="male">Male</label>
              </div>

             
            </div>


             <!-- phoen field  -->

             <div class="mb-2 mt-2">
                <label for="phone">Your Phone Number</label>
                <input
                  type="number"
                  required
                  id="phone"
                  name="phone"
                  [(ngModel)]="user.phone"
                  class="form-control rounded-0"
                  placeholder="Enter here"
                />
              </div>

              <div class="container text-center">
                <button type="submit" class="btn btn-primary">Register</button>
                <button type="reset" class="btn btn-danger ms-2">Reset Data</button>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

// react-ecom/src/components/Signup.jsx

import React, { useState } from 'react'
import {

  Container,
  Row,
  Col,
  Card, CardBody, CardTitle, Form, Input, Label, FormGroup,
  Button

} from 'reactstrap'
import { createUser } from '../services/user-service';
import { toast } from 'react-toastify'
function Signup() {



  // const [name, setName] = useState('')

  const [user, setUser] = useState({
    name: '',
    email: '',
    password: '',
    about: '',
    address: '',
    phone: '',
    gender: ''
  })

  const onFieldChange = (event, fieldName) => {
    console.log(event.target.value);
    setUser({ ...user, [fieldName]: event.target.value })

  }


  const registerUser = (event => {
    event.preventDefault()

    console.log(event)

    if (user.name.trim() === '') {
      toast.error("Username is required !!")
      return
    }

    if (user.email.trim() === '') {
      toast.error("Email is required !!")
      return;
    }

    //submit the form
    createUser(user).then((data) => {
      console.log(data)
      //alert("user registered successfully !!")
      toast.success("user registered successfully")
    }).catch(error => {
      if (error.response.status == 400) {
        // alert("validation error")
        var messages = ``
        for (let i in error.response.data) {

          messages = messages + ` ${i.toUpperCase()}  ${error.response.data[i]}  \n`

        }
        messages=messages+""
        toast.error(messages);
      } else {
        // alert("server error")
        toast.error("server error")
      }
      console.log(error)
    })

  })


  return (

    <Container>

      <Row>

        <Col md={{ size: 6, offset: 3 }}>


          <Card className='border-0 mt-3 shadow-sm'>

            <CardBody>
              <h3>Singup here </h3>
              <CardTitle>Fill fill the correct details</CardTitle>

              {/* 
              {JSON.stringify(user)} */}


              <Form onSubmit={registerUser}>

                {/* name field  */}
                <div className='mb-2 mt-4'>
                  <Label for="name" >Name</Label>
                  <Input
                    type="text"
                    id='name'
                    placeholder='Enter here'
                    onChange={(event) => onFieldChange(event, 'name')}
                    value={user.name}

                  />

                </div>
                {/* email field  */}
                <div className='mb-2 '>
                  <Label for="email" >Email </Label>
                  <Input
                    type="email"
                    id='email'
                    placeholder='Enter here'
                    onChange={(event) => onFieldChange(event, 'email')}
                    value={user.email}
                  />

                </div>
                {/* password field  */}
                <div className='mb-2 '>
                  <Label for="password" >New Password </Label>
                  <Input
                    type="password"
                    id='password'
                    placeholder='Enter here'
                    onChange={(event) => onFieldChange(event, 'password')}
                    value={user.password}

                  />

                </div>
                {/* about field  */}
                <div className='mb-2 '>
                  <Label for="about" >Something about yourself </Label>
                  <Input
                    type="textarea"
                    id='about'
                    placeholder='Enter here'
                    onChange={(event) => onFieldChange(event, 'about')}
                    value={user.about}

                  />

                </div>
                {/* address field  */}
                <div className='mb-2 '>
                  <Label for="address" >Your address </Label>
                  <Input
                    type="textarea"
                    id='address'
                    placeholder='Enter here'
                    onChange={(event) => onFieldChange(event, 'address')}
                    value={user.address}

                  />

                </div>


                {/* gender field  */}

                <FormGroup>

                  <Input
                    type='radio' name='gender'
                    checked={user.gender == 'male'}
                    onChange={(event) => onFieldChange(event, 'gender')}
                    value={'male'}

                  />
                  {' '}
                  <Label>Male</Label>



                  <Input type='radio' className='ms-3' name='gender'
                    checked={user.gender == 'female'}
                    onChange={(event) => onFieldChange(event, 'gender')}
                    value={'female'}
                  />
                  {' '}
                  <Label>Female</Label>

                </FormGroup>


                {/* phone field  */}
                <div className='mb-2 '>
                  <Label for="phone" > Phone number </Label>
                  <Input
                    type="number"
                    id='phone'
                    placeholder='Enter here'
                    onChange={(event) => onFieldChange(event, 'phone')}
                    value={user.phone}
                  />

                </div>


                <Container className='mt-2 text-center'>
                  <Button color='primary'>Register</Button>
                  <Button color='danger ms-2'>Reset Data</Button>
                </Container>

              </Form>

            </CardBody>

          </Card>



        </Col>


      </Row>


    </Container>

  )
}

export default Signup
