// angular-ecom/src/app/components/view-product/view-product.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { CartService } from 'src/app/services/cart.service';
import { ProductService } from 'src/app/services/product.service';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-view-product',
  templateUrl: './view-product.component.html',
  styleUrls: ['./view-product.component.css']
})
export class ViewProductComponent implements OnInit {
  productId: any;
  productDetail: any;
  baseUrl: string;
 
  constructor(
    private activatedRoute:ActivatedRoute,
    private product:ProductService,
    private toast:ToastrService,
    private cartService:CartService
  ) { 
    this.baseUrl=environment.baseUrl
  }

  ngOnInit(): void {


    this.activatedRoute.params.subscribe((value:any)=>{
      this.productId=value.productId
      this.getProduct();
    })

  }
  getProduct() {
   this.product.loadProductById(this.productId).subscribe({
    next:(data:any)=>{
      console.log(data);
      this.productDetail=data;
      
    },
    error:(error)=>{
      console.log(error);
      this.toast.error("Error in loading product")
      
    }
   })
  }

   //add item to card

   addToCart(){
    this.cartService.addItemToCart(this.productDetail.productId,1).subscribe({
      next:data=>{
        console.log(data);
        this.toast.success("Item added to card")
        this.cartService.cartChanged(data)
      },
      error:error=>{
        console.log(error);
        this.toast.error("Error while adding to cart")
        
      }
    })
  }


}

<div class="container" *ngIf="productDetail">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="card mt-2 border-0 shadow-sm">
        <div class="card-body">
          <h1 *ngIf="!productDetail.stock" class="text-center my-5 text-danger">
            Product is out of Stock
          </h1>
          <div *ngIf="productDetail.stock">
            <h1>{{ productDetail.productName }}</h1>
            <p class="text-muted">{{ productDetail.category.title }}</p>

            <div class="container text-center my-3">
              <img
                class="img-fluid product-image"
                [src]="baseUrl + '/products/images/' + productDetail.productId"
                alt=""
              />
            </div>

            <div class="card-text">
              Price : <b>₹ {{ productDetail.productPrice }}</b>
            </div>

            <div [innerHTML]="productDetail.productDesc"></div>

            <div class="container text-center">
              <div class="fuild-container mt-2 text-center">
                <button
                 (click)="addToCart()"
                  class="btn btn-success btn-lg"
                >
                  Add to Card
                </button>
                <button
                  class="btn btn-primary btn-lg ms-1"
                  [routerLink]="'/store/all'"
                >
                 Back
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// react-ecom/src/components/ViewProduct.jsx
import React, { useState } from 'react'
import { useEffect } from 'react'
import { Link, useParams } from 'react-router-dom'
import Base from './Base'
import { getProduct } from '../services/product-service'
import { Button, Card, CardBody, CardText, Col, Container, Row } from 'reactstrap'
import { BASE_URL } from '../services/axios-helper'
import { addItemToCart as addCart } from '../services/cart-service'
import { toast } from 'react-toastify'
import { useContext } from 'react'
import { CartProvider, context1 } from '../context'
function ViewProduct() {
    const { productId } = useParams()

    const [product, setProduct] = useState(null)

    const value = useContext(context1)

    useEffect(() => {
        // load the Product of given id 
        getProduct(productId).then((data) => {
            console.log(data)
            setProduct(data)

        }).catch(error => {
            console.log(error);
        })
    }, [])





    //add item to card
    const addItemToCart = (product) => {

        if (!product.stock) {
            toast.error("product is not in stock...")
            return;
        }

        console.log(product)
        addCart(product.productId, 1)
            .then((data) => {
                console.log(data)
                value.setCart(data)
                toast.success("Item Added to Cart")
            }).catch(error => {
                console.log(error)
            })

    }


    const productHtml = () => {
        return (
            <Card>
                <CardBody>

                    <h1>{product.productName}</h1>
                    <CardText className='text-muted'>
                        {product.category.title}
                    </CardText>

                    <div className="image-container text-center">
                        <img style={{ maxHeight: '250px' }} className='img-fluid' src={BASE_URL + '/products/images/' + product.productId} alt="" />
                    </div>

                    <CardText>

                        Price : <b> ₹ {product.productPrice}</b>

                    </CardText>

                    <CardText dangerouslySetInnerHTML={{ __html: product.productDesc }}>
                    </CardText>

                    <Container className='text-center'>
                        <Button onClick={() => addItemToCart(product)} color='success' size='lg'>Add to card</Button>
                        <Button tag={Link} to="/store/all" color='secondary' className='ms-2' size='lg'>Go Back</Button>
                    </Container>

                </CardBody>
            </Card>
        )
    }

    return (


        < Base >



            <Container>

                <Row>
                    <Col md={{ size: 10, offset: 1 }}>

                        {product &&
                            product.stock ? productHtml() : <h1 className='text-center text-danger my-5'>Product is not in stock..</h1>
                        }

                    </Col>
                </Row>

            </Container>


        </Base >
    )
}

export default ViewProduct
